// Spyglass environment manifest — single source of truth.
//
// Per Constitution v2.0.0 §I.6 (Secure-by-Default / fail-safe defaults)
// and §III.2 (typed agent semantics), env vars are declared as a typed
// Zod schema. Missing or invalid values cause `getEnv()` to throw at
// first call rather than producing undefined behavior.
//
// `.env.example` is GENERATED from this file via `pnpm gen:env-example`.
// Do not hand-edit `.env.example`. CI fails on drift between the schema
// and the example file.
//
// To add a variable:
//   1. Add a field to `envSchema` below.
//   2. Add a one-line description to `envDescriptions`.
//   3. Run `pnpm gen:env-example` and commit both.
//
// Variables marked `.optional()` are tolerated as missing in F01 but
// will be promoted to required as their consuming feature lands. The
// consuming feature ID is recorded in the description.

import { z } from "zod";

export const envSchema = z.object({
  // Runtime
  NODE_ENV: z.enum(["development", "preview", "production", "test"]).default("development"),
  VERCEL_ENV: z.enum(["development", "preview", "production"]).optional(),

  // F03 — Database (Drizzle + Neon Postgres)
  DATABASE_URL: z.string().url().optional(),

  // F08 — Parley runner / Inngest
  INNGEST_SIGNING_KEY: z.string().min(1).optional(),
  INNGEST_EVENT_KEY: z.string().min(1).optional(),

  // F02 — Auth (Clerk)
  CLERK_SECRET_KEY: z.string().min(1).optional(),
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string().min(1).optional(),
  CLERK_WEBHOOK_SIGNING_SECRET: z.string().startsWith("whsec_").optional(),
  // Comma-separated Clerk org IDs that map to the Spyglass operator
  // Organization (FR-9). Empty in dev; populated per environment.
  SPYGLASS_OPERATOR_CLERK_ORG_IDS: z.string().optional(),

  // F02 — Agent JWT signing (EdDSA, FR-18, plan Decision 4).
  // Private key as base64-encoded PKCS8 PEM. The matching public key
  // lives in the `signing_keys` table; the JWKS endpoint reads from
  // there. Bootstrap script `scripts/bootstrap-signing-key.ts` emits
  // both pieces.
  SPYGLASS_AGENT_SIGNING_KEY_PKCS8_B64: z.string().optional(),
  SPYGLASS_AGENT_SIGNING_KID: z.string().optional(),
  // Issuer URL emitted in agent JWTs (claim `iss`). Defaults per env.
  SPYGLASS_AGENT_JWT_ISSUER: z.string().url().optional(),

  // F12 — AI infrastructure (Vercel AI Gateway)
  AI_GATEWAY_API_KEY: z.string().min(1).optional(),

  // F24 — Incident response / monitoring
  SENTRY_DSN: z.string().url().optional(),

  // Integration test harness — required only when running
  // `pnpm test:integration` against Neon (otherwise the suite skips).
  NEON_API_KEY: z.string().min(1).optional(),
  NEON_PROJECT_ID: z.string().min(1).optional(),
});

export type Env = z.infer<typeof envSchema>;

/**
 * Human-readable descriptions paired with each schema key.
 * Used by `scripts/gen-env-example.ts` to generate `.env.example`.
 */
export const envDescriptions: Record<keyof Env, string> = {
  NODE_ENV: "Node runtime mode (development | preview | production | test)",
  VERCEL_ENV: "Vercel deployment context (set automatically on Vercel)",
  DATABASE_URL: "Neon Postgres connection URL — required from F03 onward",
  INNGEST_SIGNING_KEY: "Inngest webhook signing key — required from F08",
  INNGEST_EVENT_KEY: "Inngest event publish key — required from F08",
  CLERK_SECRET_KEY: "Clerk server-side secret — required from F02",
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "Clerk public key (browser-exposed) — required from F02",
  CLERK_WEBHOOK_SIGNING_SECRET:
    "Svix signing secret for the Clerk webhook endpoint (whsec_…) — required from F02 once webhooks are configured",
  SPYGLASS_OPERATOR_CLERK_ORG_IDS:
    "Comma-separated Clerk org IDs mapped to the Spyglass operator Organization (FR-9). Empty in dev.",
  SPYGLASS_AGENT_SIGNING_KEY_PKCS8_B64:
    "EdDSA private key (PKCS8 PEM, base64-encoded) for agent JWT signing. Generated by scripts/bootstrap-signing-key.ts.",
  SPYGLASS_AGENT_SIGNING_KID:
    "kid for the active EdDSA signing key — must match a row in `signing_keys` with `activated_at IS NOT NULL AND retired_at IS NULL`.",
  SPYGLASS_AGENT_JWT_ISSUER:
    "Issuer URL emitted in agent JWT `iss` claim — defaults to the Spyglass deployment URL per environment.",
  AI_GATEWAY_API_KEY: "Vercel AI Gateway API key — required from F12",
  SENTRY_DSN: "Sentry DSN — required from F24",
  NEON_API_KEY:
    "Neon API key for the integration test harness — required only by `pnpm test:integration`.",
  NEON_PROJECT_ID:
    "Neon project ID for the integration test harness — required only by `pnpm test:integration`.",
};

let cached: Env | undefined;

/**
 * Parse the given environment record (defaulting to `process.env`).
 * Tests pass an explicit record to avoid coupling to real env state.
 *
 * Throws on missing / invalid required values per Constitution §I.6.
 */
export function loadEnv(env: NodeJS.ProcessEnv = process.env): Env {
  const result = envSchema.safeParse(env);
  if (!result.success) {
    const issues = result.error.issues
      .map((i) => `  ${i.path.join(".") || "(root)"}: ${i.message}`)
      .join("\n");
    throw new Error(
      `Environment validation failed (Constitution §I.6 fail-safe defaults):\n${issues}`,
    );
  }
  return result.data;
}

export function assertMonitoringEnv(env: Env): void {
  const productionLike = env.NODE_ENV === "production" || env.VERCEL_ENV === "production";
  if (productionLike && !env.SENTRY_DSN) {
    throw new Error("F24 monitoring requires SENTRY_DSN in production-like environments");
  }
}

/**
 * Singleton accessor. First call validates `process.env`; subsequent
 * calls return the cached result. Throws on the first call if env is
 * invalid.
 *
 * Production code paths use `getEnv()`. Tests use `loadEnv(...)` with
 * an explicit env record.
 */
export function getEnv(): Env {
  if (!cached) cached = loadEnv();
  return cached;
}

/**
 * Test-only: clear the cached parsed env so subsequent `getEnv()` calls
 * re-validate. Not exported from the package's public `exports` map.
 */
export function __resetEnvCache(): void {
  cached = undefined;
}
