// F04 T005 — `seeker_tickets` table (data-model §1, §2.1).
//
// A seeker's intent-to-be-matched. Carries role family, comp band,
// jurisdictions, work mode. The state machine (draft → submitted →
// screening → matching → matched | closed | withdrawn) is enforced
// by `@spyglass/tickets`'s assertTransition at the application layer;
// the CHECK below is defense-in-depth at the DB.
//
// Identifier shape `ST-YYYY-NNNNN` is generated by the F04
// identifier allocator (Inngest-bootstrapped per-year sequences).
//
// Constitutional refs: §I.2 (state integrity), §I.4.1 (data
// minimization), §I.4.2 (retention — ticket_intent class), §I.A.1
// (jurisdiction tagging mandatory).

import { sql } from "drizzle-orm";
import {
  check,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

import { principals } from "./principals.js";

export const SEEKER_STATES = [
  "draft",
  "submitted",
  "screening",
  "matching",
  "matched",
  "closed",
  "withdrawn",
] as const;
export type SeekerTicketState = (typeof SEEKER_STATES)[number];

export const WORK_MODES = ["remote", "hybrid", "onsite"] as const;
export type WorkMode = (typeof WORK_MODES)[number];

export const seekerTickets = pgTable(
  "seeker_tickets",
  {
    seeker_ticket_id: uuid("seeker_ticket_id")
      .primaryKey()
      .default(sql`uuidv7()`),
    principal_id: uuid("principal_id")
      .notNull()
      .references(() => principals.principal_id),
    identifier: text("identifier").notNull(),
    state: text("state").notNull(),
    role_family: text("role_family").notNull(),
    comp_band_min: integer("comp_band_min").notNull(),
    comp_band_max: integer("comp_band_max").notNull(),
    currency: text("currency").notNull(),
    jurisdictions: jsonb("jurisdictions").$type<string[]>().notNull(),
    work_mode: text("work_mode").notNull(),
    flags: jsonb("flags")
      .$type<string[]>()
      .notNull()
      .default(sql`'[]'::jsonb`),
    created_at: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updated_at: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    disabled_at: timestamp("disabled_at", { withTimezone: true }),
  },
  (t) => [
    check(
      "seeker_tickets_state_check",
      sql`${t.state} IN ('draft','submitted','screening','matching','matched','closed','withdrawn')`,
    ),
    check("seeker_tickets_work_mode_check", sql`${t.work_mode} IN ('remote','hybrid','onsite')`),
    check("seeker_tickets_comp_band_order_check", sql`${t.comp_band_min} <= ${t.comp_band_max}`),
    check(
      "seeker_tickets_jurisdictions_nonempty",
      sql`jsonb_typeof(${t.jurisdictions}) = 'array' AND jsonb_array_length(${t.jurisdictions}) >= 1`,
    ),
    // FR-7: ST-YYYY-NNNNN shape. Five-digit zero-padded sequence.
    check("seeker_tickets_identifier_shape_check", sql`${t.identifier} ~ '^ST-[0-9]{4}-[0-9]{5}$'`),
    uniqueIndex("seeker_tickets_identifier_idx").on(t.identifier),
    // Hot-state listings (matching pipeline, screening dashboard).
    index("seeker_tickets_state_hot_idx")
      .on(t.state)
      .where(sql`${t.state} IN ('matching','screening')`),
    // Self-service: a seeker's own tickets newest-first.
    index("seeker_tickets_principal_idx").on(t.principal_id, t.created_at.desc()),
  ],
);

export type SeekerTicketRow = typeof seekerTickets.$inferSelect;
export type NewSeekerTicketRow = typeof seekerTickets.$inferInsert;
